version: '3.7'
services:
  spring-boot-on-docker:
    container_name: spring-boot-on-docker
    image: hyuk0628/spring-boot-on-docker:latest
    ports:
      - "80:8080"
    links:
      - mongo:mongo
    restart: always
    entrypoint: ["/bin/bash", "/entrypoint.sh", "default", "mongo", "27017"]

  mongo:
    container_name: mongo
    image: mongo:4
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_HOST: localhost
      MONGO_PORT: 27017
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: root
      APP_MONGO_USERNAME: hello
      APP_MONGO_PASSWORD: hello
      APP_MONGO_DB: hello
